const CardTable = [
  {
    value: 0,
    name: 'EDUCATION',
    color: '#007b4f',
    colorLight: '#5cffc9',
    paypal: 'donate@wikimedia.org',
    orga: 'Wikimedia Foundation',
    emoji: '📚',
    url: 'https://wikimediafoundation.org',
    description:
      'Wikimedia, known for Wikipedia, is a global movement whose mission is to bring free educational content to the world. Through various projects, chapters, and the support structure of the non-profit Wikimedia Foundation, Wikimedia strives to bring about a world in which every single human being can freely share in the sum of all knowledge. – We toast with them!',
  },
  {
    value: 1,
    name: 'ANIMALS ON EARTH',
    color: '#6631af',
    colorLight: '#da9cfd',
    paypal: 'mail@prowildlife.de',
    orga: 'Pro Wildlife',
    emoji: '🐘',
    url: 'https://www.prowildlife.de',
    description:
      'In 1999, biologists, veterinarians and people interested in nature conservation founded the animal and species protection organization Pro Wildlife. Their common goal: to improve the protection of wildlife and their habitats worldwide. They want to achieve a responsible approach to nature among the population, politicians and companies. – We toast with them!',
  },
  {
    value: 2,
    name: 'WATER FOR ALL',
    color: '#008fc3',
    colorLight: '#5cbbff',
    paypal: 'kontakt@vivaconagua.org',
    orga: 'Viva Con Agua',
    emoji: '💧',
    url: 'https://www.vivaconagua.org',
    description:
      'Viva con Agua supports water projects with the vision "WATER FOR ALL - ALL FOR WATER!". Along with the air we breathe, water is the basis of all life and a central human right. Viva con Agua pursues the vision that all people have access to clean drinking water, hygiene facilities and basic sanitation. 2.2 billion people worldwide do not have secure access to clean drinking water. Of these, around 785 million people lack even a basic supply of drinking water. – We toast with them!',
  },
  {
    value: 3,
    name: 'GOOD HEALTH',
    color: '#c98308',
    colorLight: '#fdb83f',
    paypal: 'paypal@berlin.msf.org',
    orga: 'Doctors Without Borders',
    emoji: '⛑',
    url: 'https://www.msf.org',
    description:
      'Doctors Without Borders provides emergency medical aid worldwide in crisis and war zones and after natural disasters. The international organization helps quickly, efficiently and unbureaucratically - without asking about the origin, religion or political persuasion of the people affected. – We toast with them!',
  },
  {
    value: 4,
    name: 'OUR CHILDREN',
    color: '#0071cd',
    colorLight: '#76cdff',
    paypal: 'spendenbuchhaltung@plan.de',
    orga: 'Plan International',
    emoji: '👨‍👨‍👧‍👦',
    url: 'https://plan-international.org',
    description:
      "As one of the oldest children's aid organizations, Plan International is active in more than 50 countries in Asia, Africa and Latin America - regardless of religion or politics. Over the years, the organization's work has changed significantly. From the personal commitment of Plan's founder John Langdon-Davies in 1937, one of the largest children's charities was created over the course of eight decades. – We toast with them!",
  },
  {
    value: 5,
    name: 'HUMAN RIGHTS',
    color: '#9c9302',
    colorLight: '#fff881',
    paypal: 'info@amnesty.de',
    orga: 'Amnesty International',
    emoji: '✊',
    url: 'https://www.amnesty.org',
    description:
      'Amnesty International is a global movement of more than 10 million people who take injustice personally. They are campaigning for a world where human rights are enjoyed by all. – We toast with them!',
  },
  {
    value: 6,
    name: 'BETTER CLIMATE',
    color: '#00924b',
    colorLight: '#6bff5c',
    paypal: 'lukas.kunert@elinor.network',
    orga: '#FridaysForFuture',
    emoji: '🌳',
    url: 'https://fridaysforfuture.org',
    description:
      '#FridaysForFuture is a movement that began in August 2018, after 15-year-old Greta Thunberg and other young activists sat in front of the Swedish parliament every schoolday for three weeks, to protest against the lack of action on the climate crisis. They are activists for a better climate. – We toast with them!',
  },
  {
    value: 7,
    name: 'ZERO RACISM',
    color: '#424242',
    colorLight: '#fffa76',
    paypal: 'blacklivesmatterchicago@gmail.com',
    orga: '#BlackLivesMatter',
    emoji: '✊🏿',
    url: 'https://blacklivesmatter.com',
    description:
      '#BlackLivesMatter was founded in 2013 in response to the acquittal of Trayvon Martin’s murderer. Black Lives Matter Global Network Foundation, Inc. is a global organization in the US, UK, and Canada, whose mission is to eradicate white supremacy and build local power to intervene in violence inflicted on Black communities by the state and vigilantes. By combating and countering acts of violence, creating space for Black imagination and innovation, and centering Black joy, we are winning immediate improvements in our lives. – We toast with them!',
  },
  {
    value: 8,
    name: 'THE CREATORS',
    color: '#995c7e',
    colorLight: '#f9b69c',
    paypal: 'nils.seele@gmx.de',
    orga: "Let's have a toast",
    emoji: '💡',
    url: 'https://letshaveatoast.app',
    description:
      'To the creators of letshaveatoast: If you like the idea of let’s have a toast, you can also support us, to create more such ideas. So, if you select the category "The Creators", you donate to us, the creators (Yanik, Henrik and Nils) of Let\'s Have A Toast, the corresponding donation amount. We emphasize you to give priority to the great initiatives over us! ',
  },
]
export default CardTable
