const CardTable = [
  {
    value: 0,
    name: 'BETTER CLIMATE',
    color: '#379978',
    colorLight: '#5cffc9',
    paypal: 'paypal@berlin.msf.org',
  },
  {
    value: 1,
    name: 'ANIMALS ON EARTH',
    color: '#373e99',
    colorLight: '#5c67ff',
    paypal: 'kontakt@vivaconagua.org',
  },
  {
    value: 2,
    name: 'ZERO HUNGER',
    color: '#997337',
    colorLight: '#ffc05c',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 3,
    name: 'GOOD HEALTH',
    color: '#377199',
    colorLight: '#5cbbff',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 4,
    name: 'OUR CHILDREN',
    color: '#999237',
    colorLight: '#fff55c',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 5,
    name: 'HUMAN RIGHTS',
    color: '#1565C0',
    colorLight: '#FFC107',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 6,
    name: 'FRIDAYS FOR FUTURE',
    color: '#419937',
    colorLight: '#6bff5c',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 7,
    name: 'BLACK LIVES MATTER',
    color: '#424242',
    colorLight: '#f5ff5c',
    paypal: 'henrik.geissler@googlemail.com',
  },
  {
    value: 8,
    name: 'THE CREATORS',
    color: '#995c7e',
    colorLight: '#f8e3db',
    paypal: 'henrik.geissler@googlemail.com',
  },
]
export default CardTable
